apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sdthai

resources:
- namespace.yaml
- api
- web
- ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: sdthai-food
  app.kubernetes.io/managed-by: kustomize
